server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-gateway-provider
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      shutdown-timeout: 5000
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://127.0.0.1:8341
          predicates:
            - Path=/order/**
          filters:
          - StripPrefix=1
        - id: com.biz.service.CallerService
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/api/bizCaller
          filters:
          # 第一个参数是开启过滤器，第二个是rpc对应的接口，第三个对应的是接口方法,第四个是可选的，指定 入参参数名:入参参数类型
          - SofaAdapt=true,cloud.provider.facade.CallerService,datasource,{"name":"java.lang.String"}

# LOGGING Config
logging:
  level:
    com:
      wdxxs2z:
        gateway: INFO
    org:
      springframework: INFO
  path: ./logs

# Gateway redis config
gateway:
  store:
    redis:
      enable: true
# Gateway ui config default ui: http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true

# SOFA config
com:
  alipay:
    env: shared
    instanceid: 000001
  antcloud:
    antvip:
      endpoint: acvip-inner.sofa.ynet.com
    mw:
      access:
      secret:
sofa:
  registry:
    address:
    # local:///Users/yuanshaopeng/localFileRegistry/localRegistry.reg
run:
  mode: DEV