server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-gateway-provider
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://127.0.0.1:8341
          predicates:
            - Path=/order/**
          filters:
          - StripPrefix=1

# LOGGING Config
logging:
  level:
    root: INFO
  path: ./logs/gateway

# Gateway config
gateway:
  store:
    redis:
      enable: true
# Gateway ui | http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# SOFA config
com:
  alipay:
    env: shared
    instanceid: xxxx
  antcloud:
    antvip:
      endpoint: xxx
    mw:
      access: xxx
      secret: xxx
  sofa:
    registry:
      address: local:///Users/yuanshaopeng/localFileRegistry/localRegistry.reg
run:
  mode: DEV